# Generated by Django 4.2 on 2023-04-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('number_rooms', models.IntegerField(default=1)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('is_active_in_lease', models.BooleanField(default=True)),
                ('in_rent', models.BooleanField(default=False)),
                ('prepared_for_rent', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
    ]
